Day-39

# Data Analysis --> 

In [2]:

!pip install numpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.3/14.3 MB 98.9 MB/s eta 0:00:0000:010:01


In [32]:
import numpy as np

In [40]:
# Array Creation
data = [35,25,35]
a  = np.array(data)
# a  = np.array([1,5,3])
print(a)
a

[35 25 35]


array([35, 25, 35])

In [41]:
print(a.ndim)  # return thr dimension of array
print(type(a))
print(len(a))
print(a.size) # return no.of elements in array
print(a.shape)

1
<class 'numpy.ndarray'>
3
3
(3,)


In [42]:
# 2d array

b = np.array([[1,2,3],[4,5,6]])
print(b)
b

[[1 2 3]
 [4 5 6]]


array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
print(b.ndim)  # return thr dimension of array
print(type(b))
print(len(b))
print(b.size) # return no.of elements in array
print(b.shape) # rows --> axis:0 and col-> axis:1
print(b.itemsize)

2
<class 'numpy.ndarray'>
2
6
(2, 3)
8


In [44]:
# Numpy arr vs list (Faster computation)

# let us creat list of 2

l1 = list(range(10))
l2 = list(range(10))

print(l1+l2) # merging 


# time module for time calcualtion
import time 
start = time.time()
l3 = [x+y for x,y in zip(l1,l2)]
print(l3)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [45]:
l3 = list(range(1000000))
l4 = list(range(1000000))


start = time.time()
l4 = [x+y for x,y in zip(l3,l4)]
end = time.time()

print(f"Excution Time for List is {(end-start)*1000} milliseconds")

Excution Time for List is 87.07284927368164 milliseconds


In [48]:
# creating ele in numpy arr --> arrange()


A1 = np.arange(1000000)
A2 = np.arange(1000000)
start = time.time()
A3 = A1+A2
end = time.time()
print(f"Excution Time for List is {(end-start)*1000} milliseconds")

Excution Time for List is 0.9858608245849609 milliseconds


In [49]:
# reshape ()

a = np.arange(10).reshape(2,5)
a
b = np.arange(10).reshape(5,2)
b
c = np.arange(10).reshape(5,2)
c
d = np.arange(10).reshape(2,-1)
d


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [53]:
e = np.arange(24).reshape(-1,4)
e

f = np.arange(24).reshape(3,8)
f

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [56]:
print(f+2)
print(f-2)
print(f*2)
print(f/2)

[[ 2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25]]
[[-2 -1  0  1  2  3  4  5]
 [ 6  7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20 21]]
[[ 0  2  4  6  8 10 12 14]
 [16 18 20 22 24 26 28 30]
 [32 34 36 38 40 42 44 46]]
[[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5]
 [ 4.   4.5  5.   5.5  6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5 10.  10.5 11.  11.5]]


In [59]:
a = np.array([[1,2],[3,4]])
b = np.array([[3,4],[1,2]])

print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
# statucal method 
print(np.mean(e))
print(np.median(e))
print(np.std(e))
print(np.min(e))
print(np.max(e))

print(np.minimum(a,b))

[[4 6]
 [4 6]]
[[-2 -2]
 [ 2  2]]
[[3 8]
 [3 8]]
11.5
11.5
6.922186552431729
0
23
[[1 2]
 [1 2]]


In [70]:
# indexing ansd Silcing on arrays

data = np.array([[1,4,5],[5,6,-9],[2,3,-1]])
#print(data)
print(data[0][1])
#print(data[0])

print(data[1:,1:])


4
[[ 6 -9]
 [ 3 -1]]


In [71]:
print(data[0:2,2])

[ 5 -9]


In [73]:
# range of numbers --> arrange,linespace

a = np.linspace(1,10)
a
a = np.linspace(1,10,4)
a

array([ 1.,  4.,  7., 10.])

In [74]:
a = np.linspace(1,10,4,endpoint=False,retstep=True,dtype=int)
a

(array([1, 3, 5, 7]), np.float64(2.25))

In [75]:
a = np.linspace(1,10,4,endpoint=True,retstep=True,dtype=int)
a

(array([ 1,  4,  7, 10]), np.float64(3.0))

In [81]:
# Random Number Values

b = np.random.rand()

c = np.random.randint(1,4)
c
d = np.random.randn(1,4)
d

array([[0.53252008, 0.85883688, 0.01686347, 0.76228223]])

In [86]:
#unquie values 

a = np.array([1,3,4,9,-1,2,3])
print(np.sort(a))
print(np.unique(a))

[-1  1  2  3  3  4  9]
[-1  1  2  3  4  9]


In [88]:
print(np.zeros(3))
print(np.ones((1,4)))
print(np.eye(2))


[0. 0. 0.]
[[1. 1. 1. 1.]]
[[1. 0.]
 [0. 1.]]
